### ISSUE TITLE
Doesn't work with 32-bit VMs

### ISSUE THREAD

**Issue by mshahbaz** [NetASM/NetASM-python#3]
**Error**
vagrant@coursera-sdn:~$ sudopy python /home/vagrant/pox/pox.py --no-openflow netasm.back_ends.soft_switch.datapath --address=127.0.0.1 --port=6633 --dpid=0000000000000001 --policy= --ports=s1-eth1,s1-eth2 --ctl_port=7791
POX 0.2.0 (carp) / Copyright 2011-2013 James McCauley, et al.
INFO:dp.00-00-00-00-00-01:Connecting to 127.0.0.1:6633
INFO:core:POX 0.2.0 (carp) is up.
INFO:dp.00-00-00-00-00-01:Connected to controller
ERROR:ControllerConnection(id=1):Exception handling OverflowError
Traceback (most recent call last):
File "/home/vagrant/pox/pox/datapaths/switch.py", line 1167, in read
self.on_message_received(self, msg_obj)
File "/home/vagrant/pox/pox/datapaths/switch.py", line 245, in rx_message
h(msg, connection=connection)
File "/home/vagrant/netasm/netasm/back_ends/soft_switch/datapath.py", line 472, in _rx_vendor
self._handle_out_message(message, connection)
File "/home/vagrant/netasm/netasm/back_ends/soft_switch/datapath.py", line 485, in _handle_out_message
load_policy(self, policy_name)
File "/home/vagrant/netasm/netasm/back_ends/soft_switch/datapath.py", line 184, in load_policy
policy = main()
File "/home/vagrant/netasm/netasm/examples/learning_switch_acl/learning_switch_acl_netasm.py", line 277, in main
(O.Field(Field('eth_src')), Mask(0xFFFFFFFFFFFF)))),
OverflowError: Python int too large to convert to C long
INFO:core:Going down...
INFO:core:Down.

**Comment by birukgetachew** [comment]
Is there any work around for this. My PC doesn't support VT-x, so I am using the 32 bit version of machine...

**Comment by mshahbaz** [comment]
I haven't looked into this, yet. But, folks have mentioned some workaround for this problem in the Coursera SDN Piazza forum.
https://piazza.com/class/ia0ls6utsea535?cid=656
